version: "3.19"

services:
  db:
    image: postgres:14.5-bullseye
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=Dedicace
      - POSTGRES_USER=spounka
      - POSTGRES_PASSWORD=pass123
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U spounka -d Dedicace" ]
      interval: 2s
      timeout: 3s
      retries: 5

  web:
    build: .
    command: gunicorn dedicace.wsgi --bind 0.0.0.0:8000 --workers 3
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=Dedicace
      - POSTGRES_USER=spounka
      - POSTGRES_PASSWORD=pass123
      - POSTGRES_HOST=db
    depends_on:
      db:
        condition: service_healthy

