# Generated by Django 4.1.3 on 2022-12-05 00:46

import chat.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sent', models.CharField(default='', max_length=60)),
                ('recepient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TextMessageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_message', models.CharField(default='', max_length=300)),
                ('message_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chat.chatmessageinfo')),
            ],
        ),
        migrations.CreateModel(
            name='ImageMessageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=chat.models.get_media_chat_upload_path)),
                ('message_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chat.chatmessageinfo')),
            ],
        ),
        migrations.CreateModel(
            name='VoiceMessageInfo',
            fields=[
                ('chatmessageinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chat.chatmessageinfo')),
                ('audio', models.FileField(upload_to=chat.models.get_media_chat_upload_path)),
                ('message_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voidemessage', to='chat.chatmessageinfo')),
            ],
            bases=('chat.chatmessageinfo',),
        ),
    ]
