# Generated by Django 4.1.3 on 2023-01-21 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_discussion_chatmessageinfo_discussion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussion',
            old_name='parties',
            new_name='members',
        ),
    ]
