# Generated by Django 4.1.3 on 2022-12-01 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerrequest',
            name='recepient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_recepient', to=settings.AUTH_USER_MODEL),
        ),
    ]
