# Generated by Django 4.1.3 on 2022-12-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_offerrequest_recepient'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerrequest',
            name='description',
            field=models.TextField(default='description of the offer'),
            preserve_default=False,
        ),
    ]
