# Generated by Django 4.1.3 on 2022-12-05 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_offerrequest_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availability',
            options={'verbose_name_plural': 'Availabilities'},
        ),
        migrations.AlterField(
            model_name='report',
            name='report_date',
            field=models.CharField(default='', max_length=60),
        ),
    ]
