# Generated by Django 4.1.3 on 2022-12-21 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccp', models.CharField(default='0024242424/24', max_length=50, null=True, unique=True)),
                ('rip', models.CharField(default='0079999002453623936', max_length=255, null=True, unique=True)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='ccp',
        ),
        migrations.AddConstraint(
            model_name='paymentinformation',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('ccp__isnull', True), ('rip__isnull', False)), models.Q(('ccp__isnull', False), ('rip__isnull', True)), _connector='OR'), name='ccp_or_rip_not_null'),
        ),
        migrations.AddField(
            model_name='user',
            name='payment_details',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.paymentinformation'),
        ),
    ]
