# Generated by Django 4.1.3 on 2022-12-21 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_paymentinformation_remove_user_ccp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celebrity',
            name='availability',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.availability'),
        ),
    ]
