# Generated by Django 4.1.1 on 2022-10-03 01:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_celebrity_user_alter_fan_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.PositiveBigIntegerField(default=0)),
                ('report_reason', models.TextField(default='Report Reason')),
                ('reported', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_recipient', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
