# Generated by Django 4.1.3 on 2022-12-27 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0011_alter_paymentinformation_ccp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('refused', 'Refused'),
                                            ('updated', 'Updated')], default='pending', max_length=10),
        ),
    ]
