# Generated by Django 4.1.3 on 2022-12-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_payment_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('refused', 'Refused'), ('updated', 'Updated')], default='pending', max_length=10),
        ),
    ]
