# Generated by Django 4.1.1 on 2022-10-05 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_request_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.payment'),
        ),
    ]
