# Generated by Django 4.1.1 on 2022-10-05 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_request_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='recipient',
            new_name='recepient',
        ),
    ]
