# Generated by Django 4.1.3 on 2023-01-29 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_offerrequest_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='celebrity',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
