# Generated by Django 4.1.1 on 2022-10-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_rename_recipient_request_recepient'),
    ]

    operations = [
        migrations.CreateModel(
            name='DummyImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dummy/images/')),
            ],
        ),
    ]
