# Generated by Django 4.2.1 on 2023-06-06 13:18

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_celebrity_is_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.profile_picture_upload_dir),
        ),
    ]
