# Generated by Django 4.2.1 on 2023-06-06 15:01

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.PositiveIntegerField(default=main.models.get_date_as_long),
        ),
    ]
